services:

  postgres:
    image: postgres:15
    container_name: vendor_portal_postgres
    restart: always

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d


  backend:
    build: ./backend
    container_name: vendor_portal_backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env


volumes:
  postgres_data: